In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [20]:
print(x)

[['France' 34.0 72000.0]
 ['Spain' 67.0 48000.0]
 ['Germany' 20.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 55.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 28.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [21]:
print(y)

['No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [23]:
print(x)

[['France' 34.0 72000.0]
 ['Spain' 67.0 48000.0]
 ['Germany' 20.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 55.0 58000.0]
 ['Spain' 41.0 52000.0]
 ['France' 28.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[1.0 0.0 0.0 34.0 72000.0]
 [0.0 0.0 1.0 67.0 48000.0]
 [0.0 1.0 0.0 20.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 55.0 58000.0]
 [0.0 0.0 1.0 41.0 52000.0]
 [1.0 0.0 0.0 28.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[0 0 0 0 1 1 0 1 0 1]


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [29]:
print(x_train)

[[0.0 0.0 1.0 41.0 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 34.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 67.0 48000.0]
 [1.0 0.0 0.0 28.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 55.0 58000.0]]


In [30]:
print(x_test)

[[0.0 1.0 0.0 20.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [31]:
print(y_train)

[0 1 0 0 0 1 0 1]


In [32]:
print(y_test)

[0 1]


In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [34]:
print(x_train)

[[0.0 0.0 1.0 -0.266153308430214 -1.0781259408412425]
 [0.0 1.0 0.0 -0.3513223671278825 -0.07013167641635372]
 [1.0 0.0 0.0 -0.8623367193138933 0.633562432710455]
 [0.0 0.0 1.0 -0.5216604845232194 -0.30786617274297867]
 [0.0 0.0 1.0 1.9482422177091665 -1.420463615551582]
 [1.0 0.0 0.0 -1.3733510714999042 1.232653363453549]
 [0.0 1.0 0.0 0.5003682198488023 1.5749910381638885]
 [1.0 0.0 0.0 0.9262135133371447 -0.5646194287757332]]


In [35]:
print(x_test)

[[0.0 1.0 0.0 -2.054703541081252 -0.9069571034860727]
 [1.0 0.0 0.0 -0.6068295432208879 0.2056403393225306]]
